tname: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  # Using Python 3.8 as you had previously

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==7.4.0 pandas==1.5.3  # Install compatible versions for Python 3.8

      - name: Run tests with pytest
        run: |
          chmod +x .project/tests.sh  # Ensure your test script is executable
          .project/tests.sh  # Run your test script

  

      
